import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import Button from '../components/Button'
import { StyledInput, StyledSelect, SubHeader } from '../styles/StyledComponents'
import DropDown from '../components/DropDown'
// import TextInput from '../components/TextInput';

export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to Test!
          </h1>
            <div className='asset-card'>
              <SubHeader>Buttons</SubHeader>
              <Link href="/">
                <Button primary>Navigational Button</Button>
              </Link>
              <Button  onClick={() => alert("Yay")}>Functional Button</Button>
            </div>

            <div className='asset-card'>
              <SubHeader>Standard (Styled) Form Elements</SubHeader>
              <form>
                <StyledInput type="text" placeholder="Test Text Input"></StyledInput>
                <StyledSelect>
                  <option value="Select Your Card">Select Your Car</option>
                  <option value="volvo">Volvo</option>
                  <option value="saab">Saab</option>
                  <option value="mercedes">Mercedes</option>
                  <option value="audi">Audi</option>
                </StyledSelect>
              </form>
                <Button primary onClick={() => alert("Yay")}>Submit Functional Button</Button>
            </div>

            <div className='asset-card'>
              <SubHeader>Custom Form Elements</SubHeader>
              <div>
                <DropDown title="Select Medium" />
              </div>
                <Button primary onClick={() => alert("Yay")}>Submit Functional Button</Button>
            </div>

            <div className='asset-card'>
              <SubHeader>Enter a Medium</SubHeader>
              {/* <div> */}
                {/* <TextInput fieldType="Medium"/>
              </div> */}
            </div>
            <div className='asset-card'>
              <SubHeader>Enter a Source</SubHeader>
              {/* <div> */}
                {/* <TextInput fieldType="Source"/> */}
              {/* </div> */}
            </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>

      <style jsx>{`

        .asset-card {
          background-color: #a7bcea;
          padding: 20px;
          margin: 20px;
        }

        h2 {
          font-size: 35px;
        }

      `}</style>
    </>
  )
}
